### ISSUE TITLE
Simplified Method Options

### ISSUE THREAD

**Issue by trans** [mojombo/tomdoc#17]
I was thinking about the way TomDoc handles method options. Specifically:

```
# options - The Hash options used to refine the selection (default: {}):
#           :color  - The String color to restrict by (optional).
#           :weight - The Float weight to restrict by. The weight should
#                     be specified in grams (optional).
```

It occurs to me that 99% of time "options" is always the final argument and recognized by its default `={}` regardless the actual argument name. This is Ruby's means of <i>named parameters</i>. In other words, we don't so care about the interface of the method as it is literally written (i.e. `options={}`), but rather the options that are valid to pass to it (i.e. `:color=>"#fff"`).

Based on this I would think the arguments could be written more concisely and in a way more congruent to the intent, simply:

```
# :color   - The String color to restrict by (optional).
# :weight  - The Float weight to restrict by. The weight should
#            be specified in grams (optional).
```

The actual name of the final argument `options` is inconsequential (though one could still include it if desired).

**Comment by mojombo** [comment]
This feels too loose for me. People new to Ruby or otherwise unfamiliar with TomDoc would have a hard time understanding what's going on. The current spec makes it very clear what the `options` argument is for, and what arguments it is expecting. Also, options hashes can work in a lot of different ways, and won't necessarily use symbol keys.
