### ISSUE TITLE
Metaprogramming

### ISSUE THREAD

**Issue by trans** [mojombo/tomdoc#7]
What about meta-programming. Is there any way to specify a custom attribute or method defined via dynamic means?

**Comment by mojombo** [comment]
What do you think of something like this syntax:

```
# Public: Find Records by a specific field name and value. This method
# will be available for each field defined on the record.
#
# arg - The value of the field to find by. 
#
# Returns an Array of matching Records.
### def find_by_<field>(arg)
###   ...
### end
```

The TomDoc is the same as normal, but the metaprogrammed method definitions are part of the comment and distinguished by three hash symbols, and the body of the definition is set as three dots.

This could appear anywhere in the proper scope of the file, but most likely will appear near where these methods are created.

**Comment by trans** [comment]
That's a cool idea. Though the notation seems a bit "anti-tomdocish".

I'm not sure, but playing with I it I came up with something like:

```
# Public: Find Records by a specific field name and value. This method
# will be available for each field defined on the record.
#
# arg - The value of the field to find by. 
#
# Returns an Array of matching Records.
#
# Metaprogram
#
#   def find_by_<field>(arg)
#     ...
#   end
```

**Comment by mojombo** [comment]
My goal was to keep it as similar to a regular method definition as possible while encapsulating the "code" in comments and making it obvious where the transition is. I think your syntax takes up too much room and makes the method "definition" feel more like documentation than "code".

I'm not 100% on my syntax either, but it achieves the goals that I have.

**Comment by holman** [comment]
I'm not a fan of the triple pound or the `Metaprogram` example, either. I kind of think this is interesting:

``` ruby
# Public: Find Records by a specific field name and value. This method
# will be available for each field defined on the record.
#
# arg - The value of the field to find by. 
#
# Returns an Array of matching Records.
#
#   def find_by_<field>(arg)       #
#     ...                          #
#   end                            #
```

... but the rules governing right-hand aligned hashes could be problematic. I do like how it's offset a bit more, though- since metaprogramming obscures so much of the actual source, it's nice to promote the "plaintext" version of it a bit more.

Another option might be code fencing, which I think might make a bit more sense since we're doing the triple-tick on GitHub to denote "code". Then you have a bit of a better mental model on "oh, I see triple ticks, what's coming next must be code then". Other than that, it's still fairly arbitrary, though.

`````` ruby
# Public: Find Records by a specific field name and value. This method
# will be available for each field defined on the record.
#
# arg - The value of the field to find by. 
#
# Returns an Array of matching Records.
#
# ```
#   def find_by_<field>(arg)
#     ...
#   end
# ```
``````

The drawback to these two approaches (and Tom's approach) is that there's no label that denotes that it's a simplified version of the metaprogramming, so if you're new to TomDoc it's just a little hard to grasp without reading the spec. Which kind of sucks. Maybe it's just metaprogramming that's the problem. Down with magic.

**Comment by trans** [comment]
interesting ideas. triple tick might cause conflict with normal documenting of code though.

another idea:

``` ruby
    # Public: Find Records by a specific field name and value. This method
    # will be available for each field defined on the record.
    #
    # arg - The value of the field to find by. 
    #
    # Returns an Array of matching Records.
    #
    =begin metaprogram
      def find_by_<field>(arg)
           ...
      end
    =end
```

**Comment by trans** [comment]
Oh smack! Even better:

``` ruby
  =begin metaprogram

    # Public: Find Records by a specific field name and value. This method
    # will be available for each field defined on the record.
    #
    # arg - The value of the field to find by. 
    #
    # Returns an Array of matching Records.
    #
    def find_by_<field>(arg)
         ...
    end

  =end
```

**Comment by mojombo** [comment]
I have a new approach in PR #21 that I think solves the problem better than anything we've talked about here.
